apple-web
EdSacasa/apple-web pull request #2
Opened 2019-10-24 04:43 UTC by EdSacasa

2019-10-24 04:53 UTC, EdSacasa commented
update

2019-10-24 05:05 UTC, EdSacasa commented
fixed linter erros

2019-10-24 07:27 UTC, uche-inyama requested changes
## Hi Ed :wave: 

Everything looks almost fine, just few changes to make:

- [ ] For the navigation bar, the color is not uniform, there are two shades of gray in your design. kindly fix that.
- [ ] The search field on the navigation bar is not properly positioned.

              This is how it looks on my screen

![Screenshot from 2019-10-24 08-26-08](https://user-images.githubusercontent.com/46329537/67462697-f96fd200-f637-11e9-8bb7-4e4a0df31dbd.png)

- [ ] Look below this feedback, for the other comments.

    #### ```After implementing these changes submit another for a code review.```

#### ``` Have a great day``` :slightly_smiling_face: 

@ Uchechukwu Henry Inyama

2019-10-24 07:27 UTC, uche-inyama commented on index.html
> +            <img class="w100" src="https://web.archive.org/web/20140301004610im_/http://images.apple.com/home/images/promo_supplier_responsibility_2x.jpg"  alt="Supplier Responsibility The latest res
The **```<img>tags```** should be wrapped with an **``` <a>tag```** with **```href='#'```** . When you [click](https://web.archive.org/web/20140301004610/http://www.apple.com/) on the images, they should take you to another webpage.

2019-10-24 07:27 UTC, uche-inyama commented on index.html
> +        </li>
[**OPTIONAL**]
This is not the best way to implement this design, inspect the webpage on [apple.com](https://web.archive.org/web/20140301004610/http://www.apple.com/), for reference.

2019-10-25 04:21 UTC, suretrust commented
Hi @EdSacasa,

Great job, **let's get this merged. :+1:** 

**Good luck with your future projects and happy coding!**

2019-10-25 04:33 UTC, suretrust approved these changes

2019-10-25 05:05 UTC, merged